/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x86\x85\x8d\x8f\x82\x83\x8c\x8b\x81\x89\x83\x86\x82\x80\x8b\x87\x83\x8d\x8d\x8b\x80\x8e\x82\x8c\x82\x8d\x8e\x8f\x85\x88\x8e\x8a\x8b\x87\x81\x87\x84\x8c\x83\x80\x84\x8b\x8e\x83\x86\x8a\x8c\x8b\x8d\x84\x89\x86\x8f\x89\x8e\x87\x86\x83\x8a\x83\x87\x8f\x84\x8d\x87\x8d")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x8a\x8b\x84\x88\x8b\x8f\x82\x82\x8e\x80\x8a\x85\x8d\x8c\x84\x83\x8a\x85\x8a\x81")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x87\x8b\x8f\x88\x8d\x87\x84\x82\x83\x83")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


